name: bando
description:  Application to synchronize work with lyrics for music bands.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


# Firebase
  cloud_firestore: any
  firebase_database: any
  firebase_core: any
  cloud_functions: any
  google_sign_in: any
  firebase_auth: any
  firebase_analytics: any
  firebase_storage: 5.0.0-dev.1
  firebase_crashlytics: any

# Other
  flutter_barcode_scanner: ^1.0.1
  qr_flutter: ^3.2.0
  esys_flutter_share: ^1.0.2

  dio: ^3.0.10
  http: ^0.12.2
  pdf_viewer_plugin: ^1.0.0+2
  bloc: ^6.0.3
  flutter_riverpod: ^0.10.1
  flutter_bloc: ^6.0.5
  equatable: ^1.2.0
  path_provider: ^1.6.11
  open_file: ^3.0.1
  permission_handler: ^5.0.1+1
  flutter_svg: ^0.18.1
  smooth_page_indicator: ^0.1.5
  koin: ^0.14.0
  koin_flutter: ^0.10.0
  flutter_statusbarcolor: ^0.2.3
  animations: ^1.1.1
  connectivity_widget: ^0.1.7
  lottie: any
  shared_preferences: ^0.5.8
  collection: any
  modal_bottom_sheet: ^0.2.0+1
  expandable: ^4.1.4
  flushbar: ^1.10.4


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - folder.svg
    - folder_light.svg
    - audio-doc.svg
    - audio-doc_light.svg
    - logo_gradient.png
    - logo.svg
    - google_g.svg
    - qr-code.svg
    - band.svg
    - no_group.svg
    - no_group_dark.svg
    - uploading_animation.json
    - upload.svg
    - download.svg
    - upload_download.svg
    - local_storage.svg
    - cloud.svg
    - audio-doc_deleted.svg
    - no_group_animation.json
    - empty_animation.json
    - crown.svg


  fonts:
    - family: Varela
      fonts:
        - asset: fonts/Varela.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
