name: bando
description:  An application for synchronizing work with lyrics for music bands.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: any
  firebase_core: any
  google_sign_in: any
  firebase_auth: any
  firebase_analytics: any

  flutter_barcode_scanner: ^1.0.1
  qr_flutter: ^3.2.0
  esys_flutter_share: ^1.0.2

  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  equatable: ^1.2.0
  path_provider: ^1.6.11
  open_file: ^3.0.1
  permission_handler: ^5.0.1+1
  flutter_svg: ^0.17.4
  smooth_page_indicator: ^0.1.5
  koin: ^0.10.0
  koin_flutter: ^0.6.3
  flutter_statusbarcolor: ^0.2.3
  animations: ^1.1.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - doc.svg
    - folder.svg
    - audio-doc.svg
    - logo_gradient.png
    - logo.svg
    - google_g.svg
    - qr-code.svg
    - band.svg
    - no_group.svg


  fonts:
    - family: Varela
      fonts:
        - asset: fonts/Varela.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
