name: bando
description:  Application to synchronize work with lyrics for music bands.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: any
  firebase_database: any
  firebase_core: any
  cloud_functions: any
  google_sign_in: any
  firebase_auth: any
  firebase_analytics: any
  firebase_storage: 5.0.0-dev.1
  firebase_crashlytics: any

  # http
  dio: ^3.0.10
  # BloC - state management
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  # Equality
  equatable: ^1.2.0
  # DI
  koin: ^0.14.0
  koin_flutter: ^0.10.0
  koin_bloc: ^0.1.2
  # Functional programming
  dartz: ^0.9.2
  # UI
  smooth_page_indicator: ^0.1.5
  flutter_statusbarcolor: ^0.2.3
  connectivity_widget: ^0.1.7
  expandable: ^4.1.4
  flushbar: ^1.10.4
  pdf_viewer_plugin: ^1.0.0+2
  flutter_svg: ^0.18.1
  animations: ^1.1.1
  lottie: any
  # QR
  flutter_barcode_scanner: ^1.0.1
  qr_flutter: ^3.2.0
  esys_flutter_share: ^1.0.2
  # Other
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.8
  collection: any
  transparent_image: ^1.0.0
  data_connection_checker: ^0.3.4


  cupertino_icons: ^0.1.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  dependency_validator: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - folder.svg
    - folder_light.svg
    - audio-doc.svg
    - audio-doc_light.svg
    - logo_gradient.png
    - logo.svg
    - google_g.svg
    - qr-code.svg
    - band.svg
    - no_group.svg
    - no_group_dark.svg
    - uploading_animation.json
    - upload.svg
    - download.svg
    - upload_download.svg
    - local_storage.svg
    - cloud.svg
    - audio-doc_deleted.svg
    - no_group_animation.json
    - empty_animation.json
    - crown.svg
    - en.json
    - pl.json
    - logo_transparent.png
    - forgot_pass.svg
    - no_connection.json
    - micro_b.png
    - stand.png


  fonts:
    - family: Varela
      fonts:
        - asset: fonts/Varela.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
